### ISSUE TITLE
When the CSS background image and anchor link are used, it sends request to get the anchor link

### ISSUE THREAD

**Issue by greenspeed** [craigbuckler/progressive-image.js#29] opened 2020-02-05 01:31 UTC
Every lazy loading image with bacground image and href will send a request to get the anchor link when loading the full background image. Please see below example:

Html:
`<a href="/Link-to-website"><div class="bimg progressive replace" data-bg-id="test1"></div></a>`

CSS:
 .bgimg.replace {
       background-image: url(https://lazy-loading-image.jpg);
 }

[data-bg-id='test1'] {
background-image: url(https://link-to-image.jpg);
}

**Comment by craigbuckler** [comment] 2020-02-05 09:36
Sorry, but I can't reproduce the problem.

The only way "/Link-to-website" could possibly be loaded via Ajax is if the `progressive replace` classes were assigned to the `<a>` link itself? That shouldn't be done.

Or have I misunderstood something?

**Comment by craigbuckler** [comment] 2020-02-18 14:39
No further information. Cannot reproduce. Closing.

**Closed by craigbuckler** 2020-02-18 14:39 UTC
